aed/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^craed/', include('craed.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', login),
    url(r'^accounts/logout/$', logout),
]

craed/urls.py
from django.conf.urls import url
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required, permission_required

from . import views

urlpatterns = [
    url(r'^$', views.AEDListView.as_view()),

    url(r'^list$',
        views.AEDListView.as_view(),
        name="list"),

    url(r'^detail/(?P<pk>[0-9]+)$',
        views.AEDDetailView.as_view(),
        name="detail"),
    
    url(r'^update/(?P<pk>[0-9]+)$',
        login_required(views.AEDUpdateView.as_view()),
        name="update"),

    url(r'^update$',
        login_required(views.AEDCreateView.as_view()),
        name="create"),

    url(r'^delete/(?P<pk>[0-9]+)$',
        login_required(views.AEDDeleteView.as_view()),
        name="delete"),

]

craed/models.py
from django.contrib.auth.models import User
from django.conf import settings
from django.core.urlresolvers import reverse

#from django.db import models
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point

Tijuana = Point(-117.0382, 32.5149, srid=4326)

# Create your models here.

class AED(models.Model):
    name          = models.CharField(max_length=254)
    description   = models.CharField(max_length=254, blank=True)
    location      = models.PointField(srid=4326, default=Tijuana)
    address       = models.CharField(max_length=254, blank=True)
    number        = models.PositiveIntegerField(blank=True, null=True)
    neighborhood  = models.CharField(max_length=100, blank=True)
    city          = models.CharField(max_length=100, default='Tijuana')
    state         = models.CharField(max_length=3, default='BN')
    country       = models.CharField(max_length=2, default='MX')
    public        = models.BooleanField(default=True)
    zipcode       = models.CharField(max_length=10)
    contact       = models.ForeignKey(User,
                                      on_delete=models.CASCADE)
    verified      = models.BooleanField(default=False)
    date_created  = models.DateField(auto_now_add=True)
    date_verified = models.DateField(null=True, blank=True)
    date_modified = models.DateField(auto_now=True)

    def __str__(self):
        return "{} ({:9.6f}, {:9.6f})".format(self.name, 
                                              self.location.x,  #long
                                              self.location.y); #lat
        
class Photos(models.Model):
    aed   = models.ForeignKey(AED, 
                              on_delete=models.CASCADE)
    photo = models.ImageField(upload_to = 'photos/', 
                              default = 'photos/None/no-img.jpg')

    def __str__(self):
        return "{}. {}".format(self.aed, self.photo);

craed/forms.py
from django.contrib.auth.models import User
from django.conf import settings
from django import forms
from django.contrib.gis import forms as gis_forms
from django.contrib.gis.forms import widgets as gis_widgets
from django.core.serializers import serialize

from .models import AED

class LeafletPointWidget(gis_widgets.BaseGeometryWidget):
    template_name = 'leaflet/leaflet.html'

    class Media:
        css = {
            'all': ('leaflet/css/LeafletWidget.css',)
        }
        js = (
            'http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js',
            'leaflet/js/LeafletWidget.js'
        )
        
    def render(self, name, value, attrs=None):
        # add point
        if value:
            attrs.update({ 'point': { 'x': value.x, 
                                      'y': value.y, 
                                      'z': value.z, 
                                      'srid': value.srid } 
                       })
        return super().render(name, value, attrs)

class AEDUpdateForm(forms.ModelForm):
    class Meta:
        model = AED
        fields = ['location',
                  'name', 'description',
                  'address', 'number', 'neighborhood', 
                  'city', 'state', 'country', 'zipcode',
                  'public', 'contact']
    contact = forms.ModelChoiceField(queryset=User.objects.all(), 
                                     disabled=True, empty_label=None)
    location = gis_forms.PointField(
        widget = LeafletPointWidget(attrs={'map_width': 500, 
                                           'map_height': 300}))

class AEDCreateForm(forms.ModelForm):
    class Meta:
        model = AED
        fields = ['location',
                  'name', 'description',
                  'address', 'number', 'neighborhood',
                  'city', 'state', 'country', 'zipcode',
                  'public']
    location = gis_forms.PointField(
        widget = LeafletPointWidget(attrs={'map_width': 500, 
                                           'map_height': 300}))

craed/views.py
# Create your views here.

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from braces import views

from django.http import HttpResponse
from django.http import JsonResponse
from django.template import loader

from django.contrib.gis.geos import Point

from .models import AED
from .forms import AEDUpdateForm, AEDCreateForm

class AEDListView(views.JSONResponseMixin, 
                  views.AjaxResponseMixin, 
                  ListView):
    model = AED
    context_object_name = 'aed_list'

    def get_ajax(self, request, *args, **kwargs):
        json = []
        entries = self.get_queryset()
        for entry in entries:
            json.append({
                'type': 'AED',
                'location': { 'x': entry.location.x, 
                              'y': entry.location.y },
                'name': entry.name
            })
        return self.render_json_response(json)

    def unverified(self):
        return self.request.GET.get('unverified')

    def private(self):
        return self.request.GET.get('private')

    def search(self):
        return self.request.GET.get('search')

    def nearby(self):
        return self.request.GET.get('nearby')

    def lat(self):
        return float(self.request.GET.get('lat') or 32.52174913333495)

    def lng(self):
        return float(self.request.GET.get('lng') or -117.0096155300208)
    
    def get_queryset(self, *args, **kwargs):

        # include unverified?
        if self.unverified():
            query = AED.objects.all()
        else:
            query = AED.objects.filter(verified__exact=True)

        # include private?
        if not self.private():
            query = query.filter(public__exact=True)

        # search?
        searchfor = self.search()
        if searchfor:
            query = query.filter(name__icontains=searchfor)

        return query.order_by('name')
    
class AEDDetailView(views.JSONResponseMixin, 
                    views.AjaxResponseMixin, 
                    DetailView):
    model = AED
    context_object_name = 'aed'

    def get_ajax(self, request, *args, **kwargs):
        entry = self.get_object()
        json = {
            'type': 'AED',
            'location': { 'x': entry.location.x, 
                          'y': entry.location.y },
            'name': entry.name,
            'description': entry.description,
            'address': entry.address,
            'number': entry.number,
            'neighborhood': entry.neighborhood,
            'city': entry.city,
            'state': entry.state,
            'country': entry.country,
            'zipcode': entry.zipcode,
            'public': entry.public,
            'date_created': entry.date_created,
            'date_verified': entry.date_verified,
            'date_modified': entry.date_modified,
        }
        return self.render_json_response(json)

class AEDUpdateView(UpdateView):
    model = AED
    context_object_name = 'aed'
    form_class = AEDUpdateForm
    success_url = reverse_lazy('list')
    
class AEDCreateView(CreateView):
    model = AED
    context_object_name = 'aed'
    form_class = AEDCreateForm
    success_url = reverse_lazy('list')

    def lat(self):
        return float(self.request.GET.get('lat') or 32.52174913333495)

    def lng(self):
        return float(self.request.GET.get('lng') or -117.0096155300208)

    def get_initial(self):
        point = Point(x = self.lng(), 
                      y = self.lat(), 
                      srid = 4326);
        return { 'location': point }

    def form_valid(self, form):
        # set contact to current user
        form.instance.contact = self.request.user
        return super(AEDCreateView, self).form_valid(form)

class AEDDeleteView(DeleteView):
    model = AED
    context_object_name = 'aed'
    success_url = reverse_lazy('list')

craed/templates/craed/aed_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<form action="" method="post">{% csrf_token %}
  <p>Are you sure you want to delete <i>{{ object }}</i>?</p>
  <input type="submit" value="Confirm" />
</form>

{% endblock %}

craed/templates/craed/aed_detail.html
{% extends "base.html" %}

{% block head %}
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
{% endblock %}

{% block content %}

<div style="float: left; height:200px; width:600px">
  <h2>AED Detail</h2>
  <table>
    <tr>
      <td>Name:</td>
      <td>{{ aed.name }}</td>
    </tr>
    <tr>
      <td>Public:</td>
      <td>
	<input type="checkbox" disabled="disabled" 
	       {% if aed.public %}checked="checked"{% endif %}> 
      </td>
    </tr>
    <tr>
      <td>Coordinates:</td>
      <td>({{ aed.latitude }}, {{ aed.longitude }})</td>
    </tr>
    <tr>
      <td>Description:</td>
      <td>{{ aed.description }}</td>
    </tr>
  </table>
</div>

<div id="mapid" style="width: 300px; height: 200px"></div>
<script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
<script>

  // create map
  var mymap = L.map('mapid').setView([{{ aed.latitude }}, 
                                      {{ aed.longitude }}], 13);

  // create title layer
  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWNkZW9saXZlaXJhIiwiYSI6ImNpcWR0NncxdjAyeGRmcm0xdzJ4cGlxMHgifQ.ZkRNtM3-u0mXthxqCVwjtQ', {
	 
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox.streets'
	 
  }).addTo(mymap);

  // add marker
  var marker = L.marker([{{ aed.latitude }}, 
                         {{ aed.longitude }}]).addTo(mymap);
          
  
  // AJAX test call 
  $.getJSON("http://localhost:8000/craed/detail/{{ aed.pk }}", 
    function(data) {
      console.log(data);
    }
  );

</script>

{% endblock %}

craed/templates/craed/aed_form.html
{% extends "craed/base.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" 
      href="{% static 'craed/form.css' %}" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet"
      href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
{{ form.media }}
{% endblock %}

{% block content %}

<form id="aed_form" action="" method="post">{% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <div id="buttons">
    <input class="button" id="coordinate_lookup" type="button" value="Coordinate Lookup" />
    <input class="button" id="address_lookup" type="button" value="Address Lookup" />
    {% if object %}
    <input class="button save" type="submit" value="Save" />
    <a class="button cancel" href="{{request.META.HTTP_REFERER}}">Cancel</a>
    <a class="button delete" href="{% url 'delete' object.pk %}">Delete</a>
    {% else %}
    <input class="button save" type="submit" value="Create AED" />
    {% endif %}
  </div>
</form>

<script>

  // Move map widget
  $('#id_location_div_map').detach().appendTo('#content');

</script>

{% if user.is_authenticated %}

<script>

  $('#address_lookup').click(function() {

    // lookup coordinate
    var lat = $('#id_location_lat')[0].value.trim();
    var lon = $('#id_location_lng')[0].value.trim();

    var query = encodeURI(
              'http://nominatim.openstreetmap.org/reverse?format=json'
              + '&lat=' + lat + '&lon=' + lon
              + '&zoom=18&addressdetails=1');
    console.log(query);
    $.getJSON(query,
              function(data) {
                console.log(data);
  
                if (!(data instanceof Array)) {

                  // populate form
                  if (data.address.house_number) {
                    $('#id_number')[0].value = data.address.house_number;
                  }
                  if (data.address.road) {
                    $('#id_address')[0].value = data.address.road;
                  }
                  if (data.address.neighbourhood) {
                    $('#id_neighborhood')[0].value = data.address.neighbourhood;
                  }

                  $('#id_city')[0].value = data.address.city;
                  $('#id_country')[0].value = data.address.country_code.toUpperCase();
                  $('#id_zipcode')[0].value = data.address.postcode;
  
                } else {
                  alert('Could not find address at the given coordinates');
                }
 
    });

  
  });

  $('#coordinate_lookup').click(function() {

    // lookup address
    var address = $('#id_address')[0].value;
    var number = $('#id_number')[0].value;
    var city = $('#id_city')[0].value;
    var state = $('#id_state')[0].value;
    var country = $('#id_country')[0].value;
    var zipcode = $('#id_zipcode')[0].value;

    var query = encodeURI(
             'http://nominatim.openstreetmap.org/search?format=json'
              + '&street=' + number + ' ' + address
              + '&city=' + city
              + '&state=' + state + '&countrycodes=' + country
              + '&postalcode=' + zipcode
              + '&zoom=18&addressdetails=1');
    console.log(query);
    $.getJSON(query,
              function(data) {
                console.log(data);
                console.log(data instanceof Array);

                if (data instanceof Array && data.length > 0) {
    
                  // populate form
                  geodjango_location.setPoint({lat: data[0].lat, 
                                               lon: data[0].lon });

                } else {
                  alert('Could not find coordinates of the given address');
                }
    });

  
  });

</script>

{% endif %}

{% endblock %}

craed/templates/craed/aed_list.html
{% extends "craed/base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" 
      href="{% static 'craed/list.css' %}" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet"
      href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
<script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
<script src="{% static 'leaflet/js/LeafletWidget.js' %}"></script>
<link rel="stylesheet" type="text/css" 
      href="{% static 'leaflet/css/LeafletWidget.css' %}"></link>
{% endblock %}

{% block content %}

<div id="aedlist">
  <div id="searchbox" class="bare">
    <form action="list" method="get">
      <div id="searchfieldandbutton" class="bare">
	<input id="searchfield" class="bare" type="search" name="search" 
	       placeholder="Search AEDs..."
	       {% if view.search %} value="{{ view.search }}" {% endif %}>
	<input id="searchbutton" class="bare" type="submit" value="Search"> 
      </div>
      <div id="searchoptions">
	<input class="searchoption" type="checkbox" 
	       name="nearby" value="true"
	       {% if view.nearby %} checked {% endif %}>
	<label for="nearby">nearby</label>
	<input class="searchoption" type="checkbox" 
	       name="private" value="true"
	       {% if view.private %} checked {% endif %}>
	<label for="private">private</label>
	<input class="searchoption" type="checkbox" 
	       name="unverified" value="true"
	       {% if view.unverified %} checked {% endif %}>
	<label for="unverified">unverified</label>
	<input class="hidden" type="text" name="lat"
	       value="{{ view.lat }}">
	<input class="hidden" type="text" name="lng"
	       value="{{ view.lng }}">
      </div>
    </form>
  </div>
  <div id="results">
    <ul class="aeds">
      {% if aed_list %}
      {% for aed in aed_list %}
      <li {% if not aed.verified %}
	  class="aeds unverified"
	  {% elif aed.public %}
          class="aeds public"
          {% else %}
          class="aeds private"
	  {% endif %}
	  id="{{ aed.pk }}">{{ aed.name }}</li>
      {% endfor %}
      {% else %}
      <p>No AED's found</p>
      {% endif %}
    </ul>
  </div>
</div>

<div id="mapid"></div>

<script>

  // Popup when new marker is clicked
  var newPointFunction = function(e) {
    console.log('HI');
    console.log(e);
    console.log(e.target.getPopup())

    var popup = e.target.getPopup();
    if (popup) {
      e.target.unbindPopup();
    }

    // create new popup 
    var popupContent = '<p><b>New AED</b><br/>'
        + '<p>Click here to <a href="/craed/update'
	+ '?lat=' + e.latlng.lat 
	+ '&lng=' + e.latlng.lng 
	+ '">enter details</a>';

    e.target.bindPopup(popupContent);
    
    console.log('Popup created');
    
    // center view
    widget.map.setView(e.latlng);

    // bind and open popup
    e.target.openPopup();

  }
  
  var options = {
    map_id: 'mapid',
    lat: {{ view.lat }},
    lng: {{ view.lng }},
    zoom: 13,
    newPointFunction: newPointFunction,
  };

  var widget = new LeafletMultiPointWidget(options);

  // Popup when existing marker is clicked
  var markerClicked = function(e) {

    // grab id
    var id = widget.markerIdMap[this._leaflet_id];
    
    $.getJSON("http://localhost:8000/craed/detail/" + id, 
              function(data) {

                 // unselect current item
                 $( '.aeds.selected' ).removeClass('selected');

                 // select current item
                 $( '#' + id ).addClass('selected');
     
                 // create popup 
       	         var popupContent = '<p><b>' 
                          + data.name 
                          + '</b><br/>';
                 popupContent += '<span style="font-size: small; font-style: italic;">';
	         if (data.public) {
	           popupContent += 'available for public use';
                 } else {
	           popupContent += 'private use only';
                 }
                 popupContent += '</span></p>';

	         if (data.description) {
	           popupContent += data.description;
	         }
	 
                 popupContent += '<p>';
	         if (data.address) {
	           popupContent += data.address;
                   if (data.number) {
                     popupContent += ' ' + data.number;
                   }
                   popupContent += '<br/>';
                 }
	         if (data.neighborhood) {
	           popupContent += data.neighborhood + '<br/>';
                 }
                 popupContent += data.city
                              + ', ' + data.state + ', ' 
                              + data.country + '<br/>';
                 popupContent += data.zipcode;
                 popupContent += '</p>';

                 popupContent += '<p>Created on: ' 
                        + data.date_created + '<br/>'
                        + 'Last modified on: '
	                + data.date_modified + '</p>';

                 popupContent += '<p>Click here to <a href="/craed/update/'
                        + id + '">update details</a>';

                 // center view
                 widget.map.setView(new L.LatLng(data.location.y,
                                               data.location.x));

                 // bind and open popup
                 e.target.bindPopup(popupContent).openPopup();

               });
    }

  // add points
  {% for aed in aed_list %}
    widget.addPoint({{ aed.location.y }}, {{ aed.location.x }}, 
                  {{ aed.pk }}, markerClicked);
  {% endfor %}

  // EVENT HANDLERS

  // Popup when entry is clicked
  $('li.aeds').click(function() {
      widget.markers
          .getLayer(widget.pointIdMap[$(this)[0].id])
          .fireEvent('click');
  });

</script>

{% endblock %}

craed/templates/craed/base.html
{% load static %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
  <title>{% block title %}Cruz Roja de Tijuana - AED Locator{% endblock %}</title>
  <meta charset="utf-8" />
  <script type = "text/javascript" 
          src = "http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <link rel="stylesheet" type="text/css" 
	href="{% static 'craed/style.css' %}" />
  {% block head %}{% endblock %}
</head>
<body>
  <h1>Cruz Roja de Tijuana</h1>
  <h2>Automated External Defibrillator Locator</h2>
  <ul class="menubar">
    <li class="menuitem">
      <a href="/craed/list">Home</a>
    </li>
    {% if user.is_authenticated %}
    <li class="menuitem">
      <a href="/craed/myaeds">My AEDs</a>
    </li>
    <li class="menuitem" style="float:right">
      <a href="/accounts/logout/?next={{ request.path }}">Logout</a>
    </li>
    {% else %}
    <li class="menuitem" style="float:right">
      <a href="/accounts/login/?next={{ request.path }}">Login</a>
    </li>
    {% endif %}
  </ul>
  <script>
    // make current page active
    var pname = $(location).attr('pathname').split('/',3).join('/');
    $('.menuitem a[href^="' + pname + '"]').addClass('menuitem active');
  </script>
  <div id="content">
    {% block content %}{% endblock %}
  </div>
  {% block footer %}
  {% endblock %}
  <footer>
    <nav class="footer">
      <a href="craed/about">About</a>
      <a href="craed/contact">Contact</a>
      <a href="http://www.cruzrojatijuana.org.mx">Cruz Roja de Tijuana</a>
    </nav>
  </footer>
</body>
</html>